name: street_talk
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  translator: ^0.1.7
  font_awesome_flutter: ^10.6.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  meta: ^1.9.1
  dots_indicator: ^3.0.0
  percent_indicator: ^4.2.3
  dio: ^5.4.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.6


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:

  uses-material-design: true

  
  assets:
    - assets/assets_homepage/
    - assets/flag/
    - assets/images/
    - assets/custom_icons/
    - assets/emotions_images/
    - assets/verbs/
